plugins {
    id 'net.fabricmc.fabric-loom-remap' version "${loom_version}"
    id 'maven-publish'
}

version = modpackVersion
group = 'io.github.aerhazu'

repositories {
    // Add repositories to retrieve artifacts from in here.
    // You should only use this when depending on other mods because
    // Loom adds the essential maven repositories to download Minecraft and libraries from automatically.
    // See https://docs.gradle.org/current/userguide/declaring_repositories.html
    // for more information about repositories.
}

loom {
    splitEnvironmentSourceSets()

    mods {
        "lavendre" {
            sourceSet sourceSets.main
            sourceSet sourceSets.client
        }
    }
}

dependencies {
    // To change the versions see the gradle.properties file
    minecraft "com.mojang:minecraft:${project.minecraft_version}"
    mappings "net.fabricmc:yarn:${project.yarn_mappings}:v2"
    modImplementation "net.fabricmc:fabric-loader:${project.loader_version}"

    // Fabric API. This is technically optional, but you probably want it anyway.
    modImplementation "net.fabricmc.fabric-api:fabric-api:${project.fabric_api_version}"
}

processResources {
    def version = project.version
    inputs.property "version", version

    filesMatching("fabric.mod.json") {
        expand "version": version
    }
}

tasks.withType(JavaCompile).configureEach {
    it.options.release = 21
}

java {
    // Loom will automatically attach sourcesJar to a RemapSourcesJar task and to the "build" task
    // if it is present.
    // If you remove this line, sources will not be generated.
    withSourcesJar()

    sourceCompatibility = JavaVersion.VERSION_21
    targetCompatibility = JavaVersion.VERSION_21
}

jar {
    def projectName = project.name
    inputs.property "projectName", projectName

    from("LICENSE") {
        rename { "${it}_$projectName"}
    }
}

// configure the maven publication
publishing {
    publications {
        register("mavenJava", MavenPublication) {
            from components.java
        }
    }

    // See https://docs.gradle.org/current/userguide/publishing_maven.html for information on how to set up publishing.
    repositories {
        // Add repositories to publish to here.
        // Notice: This block does NOT have the same function as the block in the top level.
        // The repositories here will be used for publishing your artifact, not for
        // retrieving dependencies.
    }
}
tasks.register("installPack", Exec) {
    group = "modpack"
    description = "Downloads Packwiz mods into the run instance"

    workingDir "run"

    doFirst {
        try {
            def connection = new URL("http://localhost:8080/pack.toml").openConnection()
            connection.setConnectTimeout(1000)
            connection.connect()
        } catch (Exception e) {
            throw new GradleException(
                    "Packwiz server is not running! Start it with: cd packwiz && packwiz serve"
            )
        }
    }

    commandLine(
            "java",
            "-jar",
            "../tools/packwiz-installer-bootstrap.jar",
            "http://localhost:8080/pack.toml"
    )
}
tasks.register("syncConfigs") {
    doLast {
        copy {
            from("run/config") {
                // Files
                include("crash_assistant/config.toml")
                include("presencefootsteps/userconfig.json")
                include("jei/jei-client.ini")
                include("betterf3.json")
                include("chatpatches.json")
                include("isxander-main-menu-credits.json")
                include("smooth_steps.json")

                // Folders
                include("fancymenu/**")
                include("sounds/**")
                include("xaero/minimap/profiles/**")
                include("simple-rpc/**")
            }

            into("packwiz/config")
        }
    }
}
///
/// [COMMAND] "./gradlew pack build=#" - Packages downloaded modpacks, resources, etc. for Modrinth upload or external launcher testing. enter build number on #. Outputs to build/distribution.
///
tasks.named("runClient") {
    dependsOn("installPack", "syncConfigs")
}
tasks.register("pack", Zip) {
    group = "modpack"
    description = "Packages the modpack for Modrinth."

    dependsOn("installPack", "syncConfigs")

    def buildNumber = project.findProperty("build")

    def fileName = "${rootProject.name}-${project.version}+${minecraftVersion}"

    if (buildNumber != null) {
        fileName += "-build-${buildNumber}"
    }

    archiveFileName.set("${fileName}.zip")
    destinationDirectory.set(layout.buildDirectory.dir("distributions"))

    // Mods
    from("run/mods") {
        into("mods")
    }

    // Configs
    from("packwiz/config") {
        into("config")
    }

    // Resource packs
    from("run/resourcepacks") {
        into("resourcepacks")
    }

    // Shader packs
    from("run/shaderpacks") {
        into("shaderpacks")
    }

    // KubeJS
    from("run/kubejs") {
        into("kubejs")
    }

    // Optional files
    from("run/options.txt")
}