name = "Lavendre"
author = "Aerhazu"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "98b804ea74e72b96268dd6113b6c5a528a24791a008a04196a13b02d4be8fa3f"

[versions]
fabric = "0.19.3"
minecraft = "1.21.4"
