name = "Lavendre"
author = "Aerhazu"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55968e1bdb5458f2aa1decf63a95e8665e9b445a87496bb7f717ac3b7a23e340"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
