name = "Lavendre"
author = "Aerhazu"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "90214a43f7b7e85d87407da31053f62d911361f765bc557a29e766e15c4fc48e"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
