name = "Lavendre"
author = "Aerhazu"
version = "0.0.1"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ef2e0cb1e76a0b980632a7f710c1cd539702a1d03449529ace6b2b1aa8b82f66"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
